version: '3.8'

services:
  sqlserver:
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    container_name: sqlserver_encrypted
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
      AKV_KEY_PATH: ${AKV_KEY_PATH}
      CEK_ENCRYPTED_VALUE: ${CEK_ENCRYPTED_VALUE}
    volumes:
      - ./sqlserver/init-sql:/docker-entrypoint-initdb.d
      - sqlserver_data:/var/opt/mssql  # Persistent storage

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
volumes:
  sqlserver_data:
